# Generated by Django 6.1.1 on 2026-09-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('bills', 'Bills'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
